name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main", "prerel", "prerel-*", "bugfix*" ]
    #~ tags: [ "*" ]
  #~ pull_request:
    #~ branches: [ "main" ]
  schedule:
  # Run every 8th of the month
  - cron: "0 2 8 * *"

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ${{ github.repository }}

jobs:

  build:
    strategy:
      matrix:
        libc: [ musl, glibc ]

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    # We first prune the container registry...
    - uses: actions/delete-package-versions@v5
      with:
        package-name: "${{ github.event.repository.name }}-${{ matrix.libc }}"
        package-type: 'container'
        min-versions-to-keep: 6
    - name: checkout repository
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}-${{ matrix.libc }}
        tags: |
          type=raw,value=latest,enable={{ is_default_branch }}
          type=raw,value={{date 'YYYYMMDD'}}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          LIBC=${{ matrix.libc }}
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE}}-${{ matrix.libc }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
